### ISSUE TITLE
problem of shuffle

### ISSUE THREAD

**Issue by AviwellLiu** [wmn7/Universal_Light#10]
after reading the code about data_augmentation_wrapper,I find you set 'self._idx = list(range(self._phase_num))',this will create a list in order,then the return of _shuffle which is 'observation[:, self._idx]' may not shuffle the lane.

**Comment by wmn7** [comment]
Hello, thank you for your interest in my work.

Regarding your question, in my experiments, I used a junction matrix where each row represents a phase. Therefore, I only need to shuffle the rows corresponding to the phases. Here is the relevant code snippet:

```
class data_augmentation_wrapper(gym.ObservationWrapper):

    def _shuffle(self, observation):
        """对 obs 中每一个时刻进行打乱顺序。例如原始是：
            array([[[0, 0, 0],
                    [1, 1, 1],
                    [2, 2, 2]],

                   [[3, 3, 3],
                    [4, 4, 4],
                    [5, 5, 5]],

                   [[6, 6, 6],
                    [7, 7, 7],
                    [8, 8, 8]]])

        转换之后变为：
            array([[[0, 0, 0],
                    [2, 2, 2],
                    [1, 1, 1]],

                   [[3, 3, 3],
                    [5, 5, 5],
                    [4, 4, 4]],

                   [[6, 6, 6],
                    [8, 8, 8],
                    [7, 7, 7]]])
        """
        self.logger.debug(f'Shuffle, {self.is_shuffle}, --> {self._idx}')
        
        # Apply the shuffle index to each 2D slice in the 3D array
        return observation[:, self._idx] # 进行乱序
```

You can refer to the original paper for more details. My analysis is based on traffic phase statistics rather than lane-based statistics.
